site_name: PyWavelets Documentation
site_url: https://pywavelets.readthedocs.io
theme:
  name: material
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - toc.follow

docs_dir: source

plugins:
  - mkdocs_matplotlib
  - include-markdown
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [../pywt]

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details

nav:
  - Home: index.md
  - install.md
  - ref/index.md
  - dev/index.md
